export interface Employee {
    id: number;
    actualContract: string | null;
    dateContractFinish: string | null;
    name: string;
    lastName: string;
    activo: number;
    id_check: number | null;
    created_at: string;
    updated_at: string;
    direction: string | null;
    cp: number | null;
    phone: string | null;
    birthday: string | null;
    rfc: string | null;
    curp: string | null;
    nss: string | null;
    school: string | null;
    ine: string | null;
    alergist: string | null;
    personalContact: string | null;
    phoneContact: string | null;
    empresa: string | null;
    puesto: string | null;
    ingreso: string | null;
    id_empleado: number | null;
    id_jefe_inmediato: number | null;
    id_departamento: number | null;
    inmBoss: string | null;
    wArea: string | null;
    infonavit: string | null;
    numCart: string | null;
    company: string | null;
    idLicNum: string | null;
    documents: any | null;
    contracts: any[];
    documentsCompany: any | null;
    removeColaborator: string | null;
    img: string | null;
    numExt: string | null;
    utalla: string | null;
    numCarttwo: string | null;
    email: string | null;
    emailCompany: string | null;
    checkCode: string | null;
    ext_tel: string | null;
}